image:
  name: sonarsource/sonar-scanner-cli:4.4
  entrypoint: [""]
variables:
  SONAR_TOKEN: $SONAR_TOKEN
  SONAR_HOST_URL: $SONAR_HOST_URL
  GIT_DEPTH: 0
sonarqube-check:
  stage: test
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: false
  only:
    - merge_requests
    - develop